openapi: 3.0.0
info:
  version: 1.0.0
  title: project API docs
  description: project API docs
  license:
    name: project

tags:
  - name: health
    description: health check 관련 API
  - name: login
    description: 사용자 인증 및 로그인 관련 API

servers:
  - url: /

paths:
  /health:
    $ref: './paths/health.yaml'
  /login:
    $ref: './paths/login.yaml'
